unus-se/app/Http/routes.php
            'roles' => ['administrator'],
        ]);

    });

    Route::auth();
    Route::get('/', function () {
        return view('welcome');
    });

    Route::get('/home', 'HomeController@index');
    Route::get('/home/notes', 'HomeController@calendarNotes');

    Route::post('/register', [
        'as' => 'auth.register',
        'uses' => 'Auth\AuthController@postRegister',
        'roles' => ['administrator'],
    ]);
    Route::get('/logout', [
        'as' => 'auth.logout',
        'uses' => 'Auth\AuthController@getLogout',
        'roles' => ['administrator', 'manager', 'user'],
    ]);
    Route::get('/login', [
        'as' => 'auth.login',
        'uses' => 'Auth\AuthController@getLogin',
    ]);
    Route::post('/login', [
        'as' => 'auth.login',
        'uses' => 'Auth\AuthController@postLogin',
    ]);

    Route::get('estados/data', [
        'as' => 'estados.data',
        'uses' => 'EstadoController@data',
        'roles' => ['administrator', 'manager', 'user'],
    ]);

    Route::resource('estados', 'EstadoController', ['except' => [
        'data'
    ]]);

    Route::get('estados/{id}/delete', [
        'as' => 'estados.delete',
        'uses' => 'EstadoController@destroy',
        'roles' => ['administrator'],

    ]);
    Route::get('estados/create', [
        'as' => 'estados.create',
        'uses' => 'EstadoController@create',
        'roles' => ['administrator', 'manager'],

    ]);

    Route::get('partidos/data', [
        'as' => 'partidos.data',
        'uses' => 'PartidoController@data',
        'roles' => ['administrator', 'manager', 'user'],

    ]);

    Route::resource('partidos', 'PartidoController', ['except' => [
        'data']]);

    Route::get('partidos/{id}/delete', [
        'as' => 'partidos.delete',
        'uses' => 'PartidoController@destroy',
        'roles' => ['administrator'],

    ]);
    Route::get('partidos/create', [
        'as' => 'partidos.create',
        'uses' => 'PartidoController@create',
        'roles' => ['administrator', 'manager'],
    ]);

    Route::get('catStatus/data', [
        'as' => 'catStatus.data',
        'uses' => 'CatStatusController@data',
        'roles' => ['administrator', 'manager', 'user'],
    ]);

    Route::resource('catStatus', 'CatStatusController');

    Route::get('catStatus/{id}/delete', [
        'as' => 'catStatus.delete',
        'uses' => 'CatStatusController@destroy',
        'roles' => ['administrator'],
    ]);

    Route::get('catStatus/create', [
        'as' => 'catStatus.create',
        'uses' => 'CatStatusController@create',
        'roles' => ['administrator', 'manager'],
    ]);

    Route::get('person/data', [
        'as' => 'person.data',
        'uses' => 'PersonController@data',
        'roles' => ['administrator', 'manager', 'user'],
    ]);

    Route::resource('person', 'PersonController', ['except' => [
        'data'
    ]]);

    Route::get('person/{id}/delete', [
        'as' => 'person.delete',
        'uses' => 'PersonController@destroy',
        'roles' => ['administrator'],
    ]);

    Route::get('person/create', [
        'as' => 'person.create',
        'uses' => 'PersonController@create',
        'roles' => ['administrator', 'manager'],
    ]);

    Route::post('person/{id}/tracking', 'PersonController@updateTracking');

    Route::get('initiatives/data', [
        'as' => 'initiatives.data',
        'uses' => 'InitiativeController@data',
        'roles' => ['administrator', 'manager', 'user'],
    ]);


    Route::resource('initiatives', 'InitiativeController', ['except' => [
        'data']]);

    Route::get('initiatives/{id}/delete', [
        'as' => 'initiatives.delete',
        'uses' => 'InitiativeController@destroy',
        'roles' => ['administrator'],
    ]);

    Route::get('initiatives/create', [
        'as' => 'initiatives.create',
        'uses' => 'InitiativeController@create',
        'roles' => ['administrator', 'manager'],
    ]);

    Route::get('catStatusPeople/data', [
        'as' => 'catStatusPeople.data',
        'uses' => 'CatStatusPersonController@data',
        'roles' => ['administrator', 'manager', 'user'],
    ]);

    Route::resource('catStatusPeople', 'CatStatusPersonController');

    Route::get('catStatusPeople/{id}/delete', [
        'as' => 'catStatusPeople.delete',
        'uses' => 'CatStatusPersonController@destroy',
        'roles' => ['administrator'],
    ]);

    Route::get('catStatusPeople/create', [
        'as' => 'catStatusPeople.create',
        'uses' => 'CatStatusPersonController@create',
        'roles' => ['administrator', 'manager', 'user'],
    ]);

    Route::get('catTipoEleccions/data', [
        'as' => 'catTipoEleccions.data',
        'uses' => 'catTipoEleccionController@data',
        'roles' => ['administrator', 'manager', 'user'],
    ]);

    Route::resource('catTipoEleccions', 'catTipoEleccionController');

    Route::get('catTipoEleccions/{id}/delete', [
        'as' => 'catTipoEleccions.delete',
        'uses' => 'catTipoEleccionController@destroy',
        'roles' => ['administrator'],

    ]);

    Route::get('catTipoEleccions/create', [
        'as' => 'catTipoEleccions.create',
        'uses' => 'catTipoEleccionController@create',
        'roles' => ['administrator', 'manager'],

    ]);


    Route::get('positions/data', [
        'as' => 'positions.data',
        'uses' => 'PositionController@data',
        'roles' => ['administrator', 'manager', 'user'],
    ]);

    Route::resource('positions', 'PositionController');

    Route::get('positions/{id}/delete', [
        'as' => 'positions.delete',
        'uses' => 'PositionController@destroy',
        'roles' => ['administrator'],

    ]);

    Route::get('positions/create', [
        'as' => 'positions.create',
        'uses' => 'PositionController@create',
        'roles' => ['administrator', 'manager'],
    ]);

    Route::get('catComisiones/data', [
        'as' => 'catComisiones.data',
        'uses' => 'catComisionesController@data',
        'roles' => ['administrator', 'manager', 'user'],
    ]);

    Route::resource('catComisiones', 'catComisionesController', ['except' => [
        'data'
    ]]);

    Route::get('catComisiones/{id}/delete', [
        'as' => 'catComisiones.delete',
        'uses' => 'catComisionesController@destroy',
        'roles' => ['administrator'],

    ]);

    Route::get('catComisiones/create', [
        'as' => 'catComisiones.create',
        'uses' => 'catComisionesController@create',
        'roles' => ['administrator', 'manager'],

    ]);

    Route::get('catDistritos/data', [
        'as' => 'catDistritos.data',
        'uses' => 'catDistritosController@data',
        'roles' => ['administrator', 'manager', 'user'],

    ]);
    Route::resource('catDistritos', 'catDistritosController');

    Route::get('catDistritos/{id}/delete', [
        'as' => 'catDistritos.delete',
        'uses' => 'catDistritosController@destroy',
        'roles' => ['administrator'],

    ]);
    Route::get('catDistritos/create', [
        'as' => 'catDistritos.create',
        'uses' => 'catDistritosController@create',
        'roles' => ['administrator', 'manager'],

    ]);

    Route::get('catCamaras/data', [
        'as' => 'catCamaras.data',
        'uses' => 'catCamaraController@data',
        'roles' => ['administrator', 'manager', 'user'],
    ]);

    Route::resource('catCamaras', 'catCamaraController');

    Route::get('catCamaras/{id}/delete', [
        'as' => 'catCamaras.delete',
        'uses' => 'catCamaraController@destroy',
        'roles' => ['administrator'],

    ]);

    Route::get('catCamaras/create', [
        'as' => 'catCamaras.create',
        'uses' => 'catCamaraController@create',
        'roles' => ['administrator', 'manager'],

    ]);

    Route::get('catTipoPersonas/data', [
        'as' => 'catTipoPersonas.data',
        'uses' => 'catTipoPersonaController@data',
        'roles' => ['administrator', 'manager', 'user'],
    ]);

    Route::resource('catTipoPersonas', 'catTipoPersonaController', ['except' => ['data']]);

    Route::get('catTipoPersonas/{id}/delete', [
        'as' => 'catTipoPersonas.delete',
        'uses' => 'catTipoPersonaController@destroy',
        'roles' => ['administrator'],

    ]);
    Route::get('catTipoPersonas/create', [
        'as' => 'catTipoPersonas.create',
        'uses' => 'catTipoPersonaController@create',
        'roles' => ['administrator', 'manager'],

    ]);

    Route::get('comisions/data', [
        'as' => 'comisions.data',
        'uses' => 'ComisionController@data',
        'roles' => ['administrator', 'manager', 'user'],
    ]);

    Route::resource('comisions', 'ComisionController');

    Route::get('comisions/{id}/delete', [
        'as' => 'comisions.delete',
        'uses' => 'ComisionController@destroy',
        'roles' => ['administrator'],

    ]);

    Route::get('comisions/create', [
        'as' => 'comisions.create',
        'uses' => 'ComisionController@create',
        'roles' => ['administrator', 'manager'],

    ]);

    Route::get('notes/data', [
        'as' => 'notes.data',
        'uses' => 'NoteController@data',
        'roles' => ['administrator', 'manager', 'user'],
    ]);

    Route::resource('notes', 'NoteController');

    Route::get('notes/{id}/delete', [
        'as' => 'notes.delete',
        'uses' => 'NoteController@destroy',
        'roles' => ['administrator'],

    ]);
    Route::get('notes/create', [
        'as' => 'notes.create',
        'uses' => 'NoteController@create',
        'roles' => ['administrator', 'manager'],

    ]);

    Route::get('catTipoComisions/data', [
        'as' => 'catTipoComisions.data',
        'uses' => 'catTipoComisionController@data',
        'roles' => ['administrator', 'manager', 'user'],
    ]);

    Route::resource('catTipoComisions', 'catTipoComisionController');

    Route::get('catTipoComisions/{id}/delete', [
        'as' => 'catTipoComisions.delete',

unus-se/app/Models/Initiative.php
<?php namespace App\Models;
use Spatie\Activitylog\LogsActivityInterface;
use Spatie\Activitylog\LogsActivity;
use Illuminate\Database\Eloquent\Model as Model;

class Initiative extends Model implements LogsActivityInterface 
{
       use LogsActivity;    
    
	public $table = "initiatives";
    

	public $fillable = [
	    "title",
		"description",
		"submit_date",
		"publication_date",
		"status_id",
		"link",
		"decree",
		"keywords",
		"fechaDecreto",
		"idCamara",
	];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        "status_id" => "integer",
		"link" => "string",
		"idCamara" => "integer",
    ];

	public static $rules = [
	    "title" => "required|max:2048",
		"description" => "required",
		"submit_date" => "required",
		"publication_date" => "required",
		"status_id" => "required",
		"persons" => "required",
		"link" => "required|max:255",
		"decree" => "max:255",
		"keywords" => "required",
		"idCamara" => "required",
		"comisiones" => "required"
	];


/**
     * Get the message that needs to be logged for the given event name.
     *
     * @param string $eventName
     * @return string
     */
    public function getActivityDescriptionForEvent($eventName)
    {
        if ($eventName == 'created')
        {
            return '{"event_type": "create", "category":"Iniciativa", "value": "'. $this->title .'"}';
        }

        if ($eventName == 'updated')
        {
            return '{"event_type": "update", "category":"Iniciativa", "value": "'. $this->title .'"}';
        }

        if ($eventName == 'deleted')
        {
            return '{"event_type": "delete", "category":"Iniciativa", "value": "'. $this->title .'"}';
        }
            return '{"event_type": "error", "category":"Iniciativa", "value": "'. $this->title .'"}';
    }



	public function persons()
    {
        return $this->belongsToMany("App\Models\Person", "person_iniciativa", "initiatives_id", "person_id")
            ->withPivot("position_id");
    }

    public function comisiones()
    {
        return $this->belongsToMany("App\Models\Comision", "iniciativa_comision", "iniciativa_id", "comision_id")
            ->withPivot("idStatusTurnado");
    }

}

unus-se/resources/views/initiatives/create.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Control Panel
            <small>Entidades</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="/initiatives/"><i class="fa fa-dashboard"></i> Entidad</a></li>
            <li class="active">Iniciativa</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Iniciativa</h3>
                        <div class="pull-right">
                            <a href="{!! route('initiatives.index') !!}" class="btn btn-primary icon-button"><i class="fa fa-list-ul"></i> Catálogo completo</a>
                        </div>
                    </div>
                    <div class="box-body">
                        @include('common.errors')

                        {!! Form::open(['route' => 'initiatives.store', 'class' => 'form-horizontal']) !!}

                        @include('initiatives.fields', ['action' => 'Crear'])

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>

@stop

unus-se/resources/views/initiatives/edit.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Control Panel
            <small>Entidades</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i>Entidad</a></li>
            <li class="active">Iniciativa</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Iniciativa</h3>
                        <div class="pull-right">
                            <a href="{!! route('initiatives.index') !!}" class="btn btn-primary icon-button"><i class="fa fa-list-ul"></i> Catálogo completo</a>
                        </div>
                    </div>
                    <div class="box-body">
                        @include('common.errors')

                        {!! Form::model($initiative, ['route' => ['initiatives.update', $initiative->id], 'method' => 'patch', 'class' => 'form-horizontal']) !!}

                        @include('initiatives.fields', ['action' => 'Actualizar'])

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>

@stop

unus-se/resources/views/initiatives/fields.blade.php
<!-- Title Field -->
<div class="form-group">
    {!! Form::label('title', 'Iniciativa', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::text('title', null, ['class' => 'form-control']) !!}
    </div>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Resumen', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
    </div>
</div>

<!-- camara Id Field -->
<div class="form-group">
    {!! Form::label('idCamara', 'Presentada En', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::select('idCamara', $idCamara, null, array('class' => 'form-control')) !!}
    </div>
</div>

<!-- Submit Date Field -->
<div class="form-group">
    {!! Form::label('submit_date', 'Fecha de Presentación', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::text('submit_date', null, ['class' => 'form-control input-date', 'placeholder' => 'dd/mm/yyyy']) !!}
    </div>
</div>

<!-- Publication Date Field -->
<div class="form-group">
    {!! Form::label('publication_date', 'Publicación en Gaceta', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::text('publication_date', null, ['class' => 'form-control input-date', 'placeholder' => 'dd/mm/yyyy']) !!}
    </div>
</div>

<!-- Decreto Date Field -->
<div class="form-group">
    {!! Form::label('fechaDecreto', 'Publicación en DOF', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::text('fechaDecreto', null, ['class' => 'form-control input-date', 'placeholder' => 'dd/mm/yyyy']) !!}
    </div>
</div>



<!-- Status Id Field -->
<div class="form-group">
    {!! Form::label('status_id', 'Estatus', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::select('status_id', $status_id, null, array('class' => 'form-control')) !!}
    </div>
</div>

<div class="form-group">
    {!! Form::label('id_person', 'Persona', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-5">
        {!! Form::select('id_person', $persons, null, ['class' => 'form-control select2']) !!}
    </div>
    {!! Form::label('id_position', 'Cargo', ['class' => 'col-sm-1 control-label']) !!}
    <div class="col-sm-3">
        {!! Form::select('id_position',  $positions, null, ['class' => 'form-control']) !!}
    </div>
    <div class="col-sm-1">
        <button type="button" class="btn btn-primary add-relation">asignar</button>
    </div>
</div>

<div class="relation-initiative-person">
    @if ($action == 'Actualizar')
        @foreach($selectedPersons as $selected)
            <div class="row initiative-person">
                <input type="hidden" name="persons[]" value="{!! $selected->id !!}">
                <input type="hidden" name="positions[]" value="{!! $selected->cargo_id !!}">
                <div class="col-sm-offset-2 col-sm-5">{!! $selected->nombre . ' ' . $selected->apellidos !!}</div>
                <div class="col-sm-offset-1 col-sm-3">{!! $selected->cargo !!}</div>
                <div class="col-sm=1">
                    <i class="fa fa-times icon-red remove-relation"></i>
                </div>
            </div>
        @endforeach
    @endif
</div>


<div class="form-group">
    {!! Form::label('id_comision', 'Comision', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-5">
        {!! Form::select('id_comision', $comisiones, null, ['class' => 'form-control select2']) !!}
    </div>
    {!! Form::label('id_turnado', 'Turnado Para:', ['class' => 'col-sm-1 control-label']) !!}
    <div class="col-sm-3">
        {!! Form::select('id_turnado',  $turnados, null, ['class' => 'form-control']) !!}
    </div>
    <div class="col-sm-1">
        <button type="button" class="btn btn-primary add-relationC">asignar</button>
    </div>
</div>


<div class="relation-initiative-comision">
    @if ($action == 'Actualizar')
        @foreach($selectedComisions as $selected)
            <div class="row initiative-comision">
                <input type="hidden" name="comisiones[]" value="{!! $selected->idComision !!}">
                <input type="hidden" name="turnados[]" value="{!! $selected->idStatus !!}">
                <div class="col-sm-offset-2 col-sm-5">{!! $selected->comision !!}</div>
                <div class="col-sm-offset-1 col-sm-3">{!! $selected->status !!}</div>
                <div class="col-sm=1">
                    <i class="fa fa-times icon-red remove-relationC"></i>
                </div>
            </div>
        @endforeach
    @endif
</div>

<!-- Link Field -->
<div class="form-group">
    {!! Form::label('link', 'Link', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::text('link', null, ['class' => 'form-control']) !!}
    </div>
</div>

<!-- Decree Field -->
<div class="form-group">
    {!! Form::label('decree', 'Decreto', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::text('decree', null, ['class' => 'form-control']) !!}
    </div>
</div>

<!-- Keywords Field -->
<div class="form-group">
    {!! Form::label('keywords', 'Keywords (tema)', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::text('keywords', null, ['id' => 'keywords', 'class' => 'form-control']) !!}
    </div>
</div>

<!-- Submit Field -->
<div class="box-footer">
    {!! Form::submit($action, ['class' => 'btn btn-primary pull-right']) !!}
</div>

@push('scripts');
<script>
    $(function () {
        var $entityKeys = $('#keywords');
        var $inputDate = $('.input-date');
        var $select = $('.select2');
        var dpOptions = {
            singleDatePicker: true,
            format: 'DD/MM/YYYY',
            locale: {
                daysOfWeek: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
                monthNames: [
                    'Enero',
                    'Febrero',
                    'Marzo',
                    'Abril',
                    'Mayo',
                    'Junio',
                    'Julio',
                    'Agosto',
                    'Septiembre',
                    'Octubre',
                    'Noviembre',
                    'Diciembre'
                ]
            }
        };

        $entityKeys.tagEditor({forceLowercase: false, placeholder: 'keyword1, keyword2, ...'});
        $inputDate.daterangepicker(dpOptions);
        $select.select2({language: "es"});
    });
</script>


<script>
    $(function () {
        var $relation = $('.add-relation');
        var $removeRel = $('.relation-initiative-person');

        var addRelation = function () {
            $person = $('#id_person');
            $position = $('#id_position');
            $relation = $('.relation-initiative-person');
            $relation.append('<div class="row initiative-person" data-person-id="' + $person.val() + '">'
                    + '<input type="hidden" name="persons[]" value="' + $person.val() + '">'
                    + '<input type="hidden" name="positions[]" value="' + $position.val() + '">'
                    + '<div class="col-sm-offset-2 col-sm-5" data-person="' + $person.val() + '">'
                    + $('#id_person option:selected').text()
                    + '</div><div class="col-sm-offset-1 col-sm-3" data-position="' + $position.val() + '">'
                    + $('#id_position option:selected').text()
                    + '</div><div class="col-sm=1"><i class="fa fa-times icon-red remove-relation"></i></div></div>');
        };

        var removeRelation = function (event) {
            $(this).closest('.row').remove();
        };

        $relation.on('click', addRelation);
        $removeRel.on('click', 'i', removeRelation);

    });
</script>


<script>
    $(function () {
        var $relationC = $('.add-relationC');
        var $removeRelC = $('.relation-initiative-comision');

        var addRelationC = function () {
            $comision = $('#id_comision');
            $turnado = $('#id_turnado');
            $relationC = $('.relation-initiative-comision');
            $relationC.append('<div class="row initiative-comision" data-comision-id="' + $comision.val() + '">'
                    + '<input type="hidden" name="comisiones[]" value="' + $comision.val() + '">'
                    + '<input type="hidden" name="turnados[]" value="' + $turnado.val() + '">'
                    + '<div class="col-sm-offset-2 col-sm-5" data-comision="' + $comision.val() + '">'
                    + $('#id_comision option:selected').text()
                    + '</div><div class="col-sm-offset-1 col-sm-3" data-turnado="' + $turnado.val() + '">'
                    + $('#id_turnado option:selected').text()
                    + '</div><div class="col-sm=1"><i class="fa fa-times icon-red remove-relationC"></i></div></div>');
        };

        var removeRelationC = function (event) {
            $(this).closest('.row').remove();
        };

        $relationC.on('click', addRelationC);
        $removeRelC.on('click', 'i', removeRelationC);

    });
</script>
@endpush

unus-se/resources/views/initiatives/index.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Control Panel
            <small>Entidades</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Entidad</a></li>
            <li class="active">Iniciativa</li>
        </ol>
    </section>

    <section class="content">
        @include('flash::message')
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Iniciativa</h3>
                        <div class="pull-right">
                            <a href="{!! route('initiatives.create') !!}" class="btn btn-primary icon-button"><i class="fa fa-plus-circle"></i> Crear Iniciativa</a>
                        </div>
                    </div>
                    <div class="box-body">
                        @if($initiatives->isEmpty())
                            <div class="well text-center">No se han encontrado Iniciativas.</div>
                        @else
                            @include('initiatives.table')
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </section>

@stop

unus-se/resources/views/initiatives/show.blade.php
@extends('layouts.app')

@section('content')

	<section class="content-header">
		<h1>
			Control Panel
			<small>Entidades</small>
		</h1>
		<ol class="breadcrumb">
			<li><a href="/home"><i class="fa fa-dashboard"></i>Entidad</a></li>
			<li class="active">Iniciativa</li>
		</ol>
	</section>

	<section class="content">
		<div class="row">
			<div class="col-md-12">
				<div class="box box-primary">
					<div class="box-header with-border">
						<h3 class="box-title">Iniciativa</h3>
						<div class="pull-right">
							<a href="{!! route('initiatives.index') !!}" class="btn btn-primary icon-button"><i class="fa fa-list-ul"></i> Listado completo</a>
						</div>
					</div>
					<div class="box-body">
						<form class="form-horizontal">
							@include('initiatives.show_fields')
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>

@stop

unus-se/resources/views/initiatives/table.blade.php
<table id="showDataTable" class="table table-striped table-bordered dt-responsive entity-tbl" cellspacing="0" width="100%">
    <thead>
    <th width="25%">Iniciativa</th>
    <th>Descripción</th>
    <th><i class="fa fa-external-link icon-small"></i> Link</th>
    <th width="50px">Acciones</th>
    </thead>
    <tfoot>
    <th>Iniciativa</th>
    <th>Descripción</th>
    <th><i class="fa fa-external-link icon-small"></i> URL</th>
    <th width="50px">Acciones</th>
    </tfoot>
    <tbody>
</table>

@push('scripts')
<script>
    $(function () {
        $('#showDataTable').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('initiatives.data') !!}',
            columns: [
                {data: 'title', name: 'title', render: function(data, type, row) {
                    return '<a href="{{ url('initiatives') }}/' + row.id + '">' + data + '</a>';
                }},
                {data: 'description', name: 'description'},
                {data: 'link', name: 'link', className: 'text-center', render: function(data, type, row) {
                    return '<a href="' + data + '" target="_blank"><i class="fa fa-file-pdf-o"></i></a>';
                }},
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ],
            language: {
                "lengthMenu": "Mostrar _MENU_ registros",
                "zeroRecords": "No se encontraron registros",
                "info": "_PAGE_ de _PAGES_",
                "infoEmpty": "Información vacía",
                "infoFiltered": "(filtrando de _MAX_ en total)",
                "search": "Buscar:",
                "processing": "Cargando...",
                paginate: {
                    previous: '‹',
                    next: '›'
                }
            }
        });
    });
</script>
@endpush